import type {
  LoveArea,
  LovePreferenceFrequency,
  LovePreferenceImportance,
  LovePreferenceTiming,
  LovePreferenceVisibility,
} from '../store/useLoveProfileStore';

export const LOVE_AREAS: LoveArea[] = [
  'emotional',
  'physicalIntimate',
  'communication',
  'financial',
  'spiritual',
  'mental',
  'social',
  'partnership',
];

export const LOVE_AREA_LABELS: Record<LoveArea, string> = {
  emotional: 'Emotional',
  physicalIntimate: 'Physical / Intimate',
  communication: 'Communication',
  financial: 'Financial',
  spiritual: 'Spiritual',
  mental: 'Mental',
  social: 'Social',
  partnership: 'Partnership',
};

export type LoveLibraryGoal =
  | 'reconnect'
  | 'reassure'
  | 'play'
  | 'support'
  | 'intimacy'
  | 'teamwork';
export type LoveLibraryEffort = 'tiny' | 'steady' | 'deep';

export const LOVE_LIBRARY_GOAL_LABELS: Record<LoveLibraryGoal, string> = {
  reconnect: 'Reconnect',
  reassure: 'Reassure',
  play: 'Play',
  support: 'Support',
  intimacy: 'Intimacy',
  teamwork: 'Teamwork',
};

export const LOVE_LIBRARY_EFFORT_LABELS: Record<LoveLibraryEffort, string> = {
  tiny: 'Tiny effort',
  steady: 'Steady effort',
  deep: 'Deep effort',
};

export const LOVE_LIBRARY_GOALS: LoveLibraryGoal[] = [
  'reconnect',
  'reassure',
  'play',
  'support',
  'intimacy',
  'teamwork',
];
export const LOVE_LIBRARY_EFFORTS: LoveLibraryEffort[] = ['tiny', 'steady', 'deep'];

export type LoveLibraryItem = {
  id: string;
  area: LoveArea;
  title: string;
  description: string;
  importance: LovePreferenceImportance;
  frequency: LovePreferenceFrequency;
  timing: LovePreferenceTiming;
  visibility: LovePreferenceVisibility;
  customTiming?: string;
  goal: LoveLibraryGoal;
  effort: LoveLibraryEffort;
  featured?: boolean;
  tags: string[];
};

export const LOVE_LIBRARY_ITEMS: LoveLibraryItem[] = [
  {
    id: 'lib-emotional-1',
    area: 'emotional',
    title: 'Warm reunion hug',
    description: 'Give me a long hug and a soft check-in when we reconnect after work.',
    importance: 'high',
    frequency: 'severalTimesWeekly',
    timing: 'evening',
    visibility: 'shared',
    goal: 'reconnect',
    effort: 'tiny',
    featured: true,
    tags: ['after work', 'hug', 'arrival', 'soft landing'],
  },
  {
    id: 'lib-emotional-2',
    area: 'emotional',
    title: 'Gentle reassurance',
    description: 'Tell me directly that we are okay when stress starts to build.',
    importance: 'essential',
    frequency: 'weekly',
    timing: 'anytime',
    visibility: 'shared',
    goal: 'reassure',
    effort: 'tiny',
    featured: true,
    tags: ['anxiety', 'security', 'calm', 'check-in'],
  },
  {
    id: 'lib-emotional-3',
    area: 'emotional',
    title: 'Name what you notice',
    description: 'Say one specific thing you appreciate about how I showed up today.',
    importance: 'high',
    frequency: 'daily',
    timing: 'evening',
    visibility: 'shared',
    goal: 'reassure',
    effort: 'tiny',
    tags: ['affirmation', 'seen', 'appreciation', 'daily'],
  },
  {
    id: 'lib-physical-1',
    area: 'physicalIntimate',
    title: 'Slow touch',
    description: 'Initiate affectionate touch without rushing toward an outcome.',
    importance: 'high',
    frequency: 'weekly',
    timing: 'evening',
    visibility: 'surprise',
    goal: 'intimacy',
    effort: 'steady',
    featured: true,
    tags: ['touch', 'non-sexual', 'gentle', 'presence'],
  },
  {
    id: 'lib-physical-2',
    area: 'physicalIntimate',
    title: 'Unhurried cuddle',
    description: 'Stay close for ten full minutes with no phones and no multitasking.',
    importance: 'medium',
    frequency: 'weekly',
    timing: 'evening',
    visibility: 'shared',
    goal: 'reconnect',
    effort: 'steady',
    tags: ['cuddle', 'touch', 'rest', 'presence'],
  },
  {
    id: 'lib-communication-1',
    area: 'communication',
    title: 'Clear check-in',
    description: 'Ask what I need tonight instead of making me guess your energy.',
    importance: 'high',
    frequency: 'daily',
    timing: 'anytime',
    visibility: 'shared',
    goal: 'support',
    effort: 'tiny',
    featured: true,
    tags: ['clarity', 'questions', 'needs', 'daily'],
  },
  {
    id: 'lib-communication-2',
    area: 'communication',
    title: 'Repair faster',
    description: 'If tension spikes, circle back the same day instead of letting distance harden.',
    importance: 'essential',
    frequency: 'occasionally',
    timing: 'custom',
    visibility: 'shared',
    customTiming: 'The same day after conflict or distance',
    goal: 'reassure',
    effort: 'deep',
    tags: ['repair', 'conflict', 'return', 'safety'],
  },
  {
    id: 'lib-financial-1',
    area: 'financial',
    title: 'Money rhythm',
    description: 'Set a calm weekly money check-in so finances feel shared, not avoided.',
    importance: 'medium',
    frequency: 'weekly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'teamwork',
    effort: 'steady',
    tags: ['budget', 'planning', 'clarity', 'weekly'],
  },
  {
    id: 'lib-financial-2',
    area: 'financial',
    title: 'Small relief offer',
    description: 'Ask if there is one errand, bill, or money task you can take off my plate this week.',
    importance: 'medium',
    frequency: 'weekly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'support',
    effort: 'steady',
    tags: ['support', 'stress', 'errand', 'shared load'],
  },
  {
    id: 'lib-spiritual-1',
    area: 'spiritual',
    title: 'Shared grounding',
    description: 'Pause together for prayer, gratitude, or quiet reflection once a week.',
    importance: 'medium',
    frequency: 'weekly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'reconnect',
    effort: 'steady',
    tags: ['prayer', 'gratitude', 'reflection', 'peace'],
  },
  {
    id: 'lib-spiritual-2',
    area: 'spiritual',
    title: 'Bless the hard week',
    description: 'Before sleep, speak hope over what has been heavy instead of pretending we are fine.',
    importance: 'high',
    frequency: 'occasionally',
    timing: 'evening',
    visibility: 'shared',
    goal: 'reassure',
    effort: 'deep',
    tags: ['hope', 'night', 'blessing', 'hard week'],
  },
  {
    id: 'lib-mental-1',
    area: 'mental',
    title: 'Protect my focus',
    description: 'Help me create uninterrupted space when my mind feels overloaded.',
    importance: 'medium',
    frequency: 'occasionally',
    timing: 'custom',
    visibility: 'private',
    customTiming: 'When my mind feels overloaded',
    goal: 'support',
    effort: 'steady',
    featured: true,
    tags: ['focus', 'overwhelm', 'mental load', 'space'],
  },
  {
    id: 'lib-mental-2',
    area: 'mental',
    title: 'Decision relief',
    description: 'Take the lead on one small decision when my brain is tired and options feel noisy.',
    importance: 'medium',
    frequency: 'occasionally',
    timing: 'custom',
    visibility: 'shared',
    customTiming: 'When I am decision-fatigued',
    goal: 'support',
    effort: 'tiny',
    tags: ['decision fatigue', 'support', 'leadership', 'clarity'],
  },
  {
    id: 'lib-social-1',
    area: 'social',
    title: 'Intentional outing',
    description: 'Plan a simple social moment that helps us feel alive together.',
    importance: 'medium',
    frequency: 'monthly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'play',
    effort: 'steady',
    tags: ['date', 'outings', 'joy', 'energy'],
  },
  {
    id: 'lib-social-2',
    area: 'social',
    title: 'Leave the phones away',
    description: 'Choose one hour for us where the phones stay down and our attention stays with each other.',
    importance: 'high',
    frequency: 'weekly',
    timing: 'evening',
    visibility: 'shared',
    goal: 'reconnect',
    effort: 'tiny',
    tags: ['presence', 'phones', 'attention', 'date'],
  },
  {
    id: 'lib-partnership-1',
    area: 'partnership',
    title: 'Shared load',
    description: 'Take initiative on one practical task so I feel supported, not alone.',
    importance: 'high',
    frequency: 'weekly',
    timing: 'anytime',
    visibility: 'shared',
    goal: 'teamwork',
    effort: 'steady',
    featured: true,
    tags: ['household', 'support', 'initiative', 'partnership'],
  },
  {
    id: 'lib-partnership-2',
    area: 'partnership',
    title: 'Plan the next gentle thing',
    description: 'Before the week gets loud, set one small plan we can both look forward to together.',
    importance: 'medium',
    frequency: 'weekly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'teamwork',
    effort: 'steady',
    tags: ['planning', 'calendar', 'anticipation', 'together'],
  },
  {
    id: 'lib-play-1',
    area: 'social',
    title: 'Flirty interruption',
    description: 'Send a playful check-in during the day that reminds me I am still on your mind.',
    importance: 'medium',
    frequency: 'severalTimesWeekly',
    timing: 'anytime',
    visibility: 'surprise',
    goal: 'play',
    effort: 'tiny',
    featured: true,
    tags: ['text', 'playful', 'daytime', 'attention'],
  },
  {
    id: 'lib-intimacy-1',
    area: 'physicalIntimate',
    title: 'Set the scene softly',
    description: 'Create a slower intimate atmosphere before asking me to jump into desire.',
    importance: 'high',
    frequency: 'occasionally',
    timing: 'evening',
    visibility: 'surprise',
    goal: 'intimacy',
    effort: 'deep',
    tags: ['atmosphere', 'desire', 'slow', 'care'],
  },
  {
    id: 'lib-support-1',
    area: 'partnership',
    title: 'Ask where the load is heaviest',
    description: 'Ask where I feel most alone this week and choose one way to help carry it.',
    importance: 'high',
    frequency: 'weekly',
    timing: 'weekend',
    visibility: 'shared',
    goal: 'support',
    effort: 'deep',
    tags: ['empathy', 'shared load', 'care', 'check-in'],
  },
];
